title: "Manikandaraj Srinivasa"
description: "My personal blog about technology, programming, and life experiences."
baseurl: ""
url: "https://manikandaraj.github.io"

# Theme
remote_theme: pages-themes/hacker@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Default settings for blog posts
defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"