title: My Blog
# Set the theme to 'hacker' from GitHub Pages Themes
theme: jekyll-theme-hacker

# Optional: Add other configuration options below
# description: A blog powered by Jekyll and the Hacker theme
# author: Your Name
