title: "Manikandaraj Srinivasan"
description: "My personal blog about technology, programming, and life experiences."
baseurl: ""
#url: "https://manikandaraj.github.io"

# Theme
remote_theme: pages-themes/hacker@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Hide GitHub button
github:
  is_project_page: false

# Default settings for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"