title: "Manikandaraj Srinivasa"
description: "My personal blog about technology, programming, and life experiences."
baseurl: ""
url: "https://manikandaraj.github.io"

# Theme
theme: Hacker  # or any other supported theme

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Default settings for blog posts
defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"