title: "Manikandaraj Srinivasan"
description: "My personal blog about technology, programming, and life experiences."
baseurl: ""
#url: "https://manikandaraj.github.io"

# Theme
remote_theme: pages-themes/hacker@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge

# Kramdown settings for better table support
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Hide GitHub button
github:
  is_project_page: false

# Default settings for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"